version: "3.9"

services:
  my-app:
    build:
      dockerfile: ./Dockerfile-app
      context: ./
    environment:
      SQLALCHEMY_DATABASE_URI: postgresql://username:passwd@pg:5432/blog

    volumes:
      - ./:/app
    ports:
      - "5050:5000"

  pg:
    image: postgres
    env_file:
      - ./pg.env
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  db-data:
